### ISSUE TITLE
Half bars ?

### ISSUE THREAD

**Issue by gilou** [bobthekingofegypt/BobBall#14]
Hi !
In the original JezzBall, you could create a half bar as soon as one half was completed on the previous click.. Would be lovely to have that!

Cheers, and thanks for BobBall ;)

**Comment by guerda** [comment]
Do you mean that you start growing another half bar while the old bar is still growing in one half?

**Comment by gilou** [comment]
yes, you start a bar, one half finishes, you can start another half on its own somewhere else. See the original Jezzball or Icebreaker on Linux to get an idea. It allows you to start an unbalanced bar: say north/south, you click on the bottom of the screen, the south part is quickly done while the north is growing, you can start another half bar going south. See the attached image on Icebreaker, I started such a bar on the right end of the screen (north/south), south finished, I started another one (red one, going south).

![icebreaker](https://cloud.githubusercontent.com/assets/2179770/10157898/62f4de0c-668e-11e5-8d6d-be08bd9ada27.png)

**Comment by rnauber** [comment]
That would be a nice addition! If someone wants to implement this, this is a good starting point:

org/bobstuff/bobball/GameEventQueue.java:289

See you,
Richard

**Comment by rnauber** [comment]
Thanks to @wesen1 #22 this is implemented in v1.12.1.
Have fun!
