### ISSUE TITLE
Include BobBall in the Fdroid repository

### ISSUE THREAD

**Issue by rnauber** [bobthekingofegypt/BobBall#2]
Hi there,
thank you @bobthekingofegypt  for creating such a great and addictive  game! It would be really nice to make it available for a wider audience, especially for the users of fdroid.
Getting the game into their repository is quite simple (https://f-droid.org/manual/fdroid.html), its just a matter of creating a textfile like this:

metadata/org.bobstuff.bobball.txt

```
Categories:None
License:Unknown
Web Site:
Source Code:https://github.com/rnauber/BobBall.git
Issue Tracker:https://github.com/rnauber/BobBall.git/issues

Summary:
Description:
.

Repo Type:git
Repo:https://github.com/rnauber/BobBall.git

Build:1.0,1
 commit=33e0e57aedf0c5efbfdc2c778c13e1c2d873be8f

Auto Update Mode:None
Update Check Mode:Tags
```

So could you please fetch my  pull request and then we could ask at https://f-droid.org/forums/forum/submission-queue/ for inclusion in the repository.

Have a nice day,
Richard

**Comment by bobthekingofegypt** [comment]
Hello, sadly I'm a little busy just now to look into this - I've kind of abandoned this project after I lost the Play Store key and couldn't update it. 

But I've given you collaborator permission so you can add any files you wish.

**Comment by rnauber** [comment]
Hi,
your game should now be included in the fdroid repository:
https://f-droid.org/forums/topic/bobball/

And I took the liberty in tagging the current master as "v1.0"...

Thanks again for this nice little game,
Richard
