### ISSUE TITLE
Pause menu doesn't cover the whole screen

### ISSUE THREAD

**Issue by jurf** [bobthekingofegypt/BobBall#25]
I have a 480 times 900 something screen and the pause menu only cover about two-thirds of the screen.

**Comment by rnauber** [comment]
That is intended, it is a drawer you pull out of you phone. You can push it back to the left if you want...

**Comment by jurf** [comment]
Oh, didn't notice that, thanks. But what about the start menu?

**Comment by rnauber** [comment]
Its all the same. But that the menu is a drawer needs to be more obvious. Do you have any suggestions, maybe we should tint it?

**Comment by jurf** [comment]
Add a border on the right side.

**Comment by rnauber** [comment]
Fixed by @wesen1 in #33 ! Thank you!
