### ISSUE TITLE
Time should increase slightly as the levels increase

### ISSUE THREAD

**Issue by jasonmacduffie** [bobthekingofegypt/BobBall#26]
This is a matter of opinion, but I think the game currently has a very steep curve as it approaches levels 8 or 9, then it seems nearly impossible. The game would still be difficult if a few seconds were added after each level to accommodate the greater number of balls.

**Comment by rnauber** [comment]
So should we give a fixed amount of time per ball?

**Comment by wesen1** [comment]
In the original game, the displayed time per level is 1250 + level \* 250 . I think it's a good idea to have more time on levels with more balls, because you often have to wait for an opportunity to draw a line on later levels.

**Comment by rnauber** [comment]
Sounds good, so do you want to go ahead and implement it?
