### ISSUE TITLE
can't read info on nexus 10

### ISSUE THREAD

**Issue by Foggalong** [bobthekingofegypt/BobBall#3]
![tmp_20425-screenshot_2015-07-30-00-30-32-1171513120](https://cloud.githubusercontent.com/assets/5920259/8972465/5e4b09b0-3652-11e5-8434-2bc260f38742.png)

**Comment by rnauber** [comment]
Hi Joshua,
I tried to improve the layout a little, so please test the new version v1.1.

See you,
Richard

**Comment by Foggalong** [comment]
Sorry for the delay, been on holiday. The new interface is a billion times better. Much thanks <3
![tmp_2109-screenshot_2015-08-16-01-17-521386465169](https://cloud.githubusercontent.com/assets/5920259/9291410/af5fb06a-43b5-11e5-833c-8d37fc6f5b82.png)
