### ISSUE TITLE
ball teleports

### ISSUE THREAD

**Issue by imkarjala** [bobthekingofegypt/BobBall#4]
On level 5, after I’ve segregated the balls into individual cells, sometimes one of the balls will disappear from it’s cell and reappear in another one.

I don't know if this is a bug or part of the design, but it feels like a bug.

**Comment by rnauber** [comment]
Well, the author of  BobBall designed it to be an accurate quantum physics simulator disguised as innocent game. So it is a feature instead of a bug! But you might want to try out  v1.5 and see if it changes something ...
