### ISSUE TITLE
Feature request: add a play/pause button

### ISSUE THREAD

**Issue by Ezelty** [bobthekingofegypt/BobBall#5]
There's no way to make a pause while playing the game.
If I turn my phone's screen off between two levels, there's a bug when I turn it on: the game starts over instead of playing the next level.
Therefore, a play/pause button would be useful.

**Comment by arbie65** [comment]
a pause option was adding in, as far as I can tell v 1.6.  There is a bit of an issue with it though as seen in ticket #6.

I've also created a ticket ( #7 ) for the screen sleep / lock issue
