### ISSUE TITLE
unable to quit the game using back button

### ISSUE THREAD

**Issue by arbie65** [bobthekingofegypt/BobBall#6]
Following an upgrade to v1.6 it looks like a pause feature has been implemented when you press the back button instead of just leaving the game.

The has had the downside that you can no longer leave the app by pressing the back button.

Suggestion that when back button is pressed it pauses the game and you are given two options.
1. Resume game
2. Quit game  

It would also be useful if a second press of back button exited the game.

**Comment by arbie65** [comment]
Also if you have lost a game and the try again screen is up.  if you press back it "pauses" the game that is not happening

**Comment by rnauber** [comment]
I think the nicest solution would be to press back once and the game pauses and to press it again to exit the game. Agreed? Then I am going to implement this... (and fix the pause after dead bug)

Thanks for reporting this bug,
Richard

**Comment by arbie65** [comment]
> I think the nicest solution would be to press back once and the game pauses and to press it again to exit the game. Agreed?

Yes. I would be happy with that solution.

**Comment by rnauber** [comment]
Ok, this is implemented in v1.7.  Please test it...

Bye,
Richard

**Comment by arbie65** [comment]
v1.7 won't even start, just crashes on CyanogenMod 11 with no option for logs that I can find

```
unfortunately bobball has stopped
                   [ ok ]
```

**Comment by rnauber** [comment]
Oh, that"s unfortunate... You may try to use an app like this
https://f-droid.org/repository/browse/?fdfilter=logcat&fdid=rs.pedjaapps.alogcatroot.app
to get a log. Otherwise it is hard to hunt down this nasty bug.

Thank you for reporting this bug,
Richard

**Comment by JavaJens** [comment]
I have the same issue that the latest version doesn't even start, that is on Sony z3c android 5.1

Sadly I don't have root. But I try to get a logcat from the desktop. 
I guess this should move to a new issue though

**Comment by rnauber** [comment]
Ok, I think the original issue should be fixed...

**Comment by arbie65** [comment]
yes, thank you
