### ISSUE TITLE
screen lock / sleep results in game restarting at level 1

### ISSUE THREAD

**Issue by arbie65** [bobthekingofegypt/BobBall#7]
Splitting this out from #5.

There is a bug that if the screen goes to sleep or you lock it, either mid game, game paused or at the game over screen, bobball will reset and start a new game at level 1.

**Comment by rnauber** [comment]
Oh boy, to fix that bug the state of the game must be saved.That means we need to make the class "GameManager" parcel-able, so we can retain its state. 
I think it will take me a while to implement this, maybe someone else want to give it a shot? Patches are welcome!

Thanks for reporting this bug,
Richard

**Comment by rnauber** [comment]
Ok, this should be fixed with v1.7. Please test it thoroughly and do not cry if it eats your highscore..
Bye,
Richard
