### ISSUE TITLE
Crash on launch for 1.7 update

### ISSUE THREAD

**Issue by zerps** [bobthekingofegypt/BobBall#8]
I updated to version 1.7 from the fdroid repo this morning, and now the app crashes as soon as I touch the button to open it. "Unfortunately, BobBall has stopped"

Nexus 5 phone and stock android 5.1.1

Everything was working fine prior to the update.

**Comment by rnauber** [comment]
Ok, I think it should be fixed with v1.7.1...

Thanks for reporting the bug,
Richard

**Comment by deniss-s** [comment]
The same crash is with CM11 and CM12. I managed to launch the app only with auto-rotate mode on and holding the phone in landscape orientation.

**Comment by JavaJens** [comment]
This was fixed for me in update 1.7.1. Thanks for the fast fix!

**Comment by arbie65** [comment]
reported this in comments of #7, confirming it's fixed now for me
